name: NoSwear
version: 7.3
description: Control your chat.
softdepend: [Vault]
author: A5H73Y
main: me.A5H73Y.NoSwear.NoSwear
api-version: 1.13
commands:
  noswear:
    aliases: [ns]
    description: NoSwear commands